pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh "pwd"
                sh "cd /var/jenkins_home/workspace/jenkinscloud/jenkinscloud"
                sh "pwd"
                sh "ls -ll"
                sh 'mvn -B -X -DskipTests clean package'
            }
        }

    }
}

